# This CI/CD configuration setup was inspired by https://github.com/jsakamoto/PublishSPAforGitHubPages.Build

name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: src

      - name: Run Tests
        run: dotnet test --configuration Release --no-build
        working-directory: src

      - name: Create Artifacts
        run: dotnet publish BF2Dashboard.UI/BF2Dashboard.UI.csproj -c:Release -o:../public -p:GHPages=true -p:GHPagesBase=.
        working-directory: src

      - name: Deploy Artifacts to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/wwwroot
          force_orphan: true
          cname: "bf2.tv"
          user_name: "TwitchPlaysBF2"
          user_email: "89540386+TwitchPlaysBF2@users.noreply.github.com"
          commit_message: "Deploys: "